steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oauth2-server-rs:0.3.2', '.']
timeout: '1600s'
images: ['gcr.io/$PROJECT_ID/oauth2-server-rs:0.3.2']
options:
  machineType: E2_HIGHCPU_8
