steps:
  - name: 'gcr.io/$PROJECT_ID/cargo'
    args: ['build', '--release']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oauth2-server-rs:0.2.0', '.']
timeout: '1600s'
images: ['gcr.io/$PROJECT_ID/oauth2-server-rs:0.2.0']
