steps:
  - name: 'gcr.io/$PROJECT_ID/cargo'
    args: ['build', '--release']
    timeout: '1600s'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oauth2-server-rs:0.2.0', '.']
images: ['gcr.io/$PROJECT_ID/oauth2-server-rs:0.2.0']
