apiVersion: serving.knative.dev/v1
kind: Service
metadata: 
  name: "oauth2-tokenserver"
spec:
  template:
    spec:
      containers:
      - image: "gcr.io/$PROJECT_ID/oauth2-server-rs:0.3.0"
        env:
        - name: bootstrap
          value: 'false'
        - name: SERVER.HOST
          value: 0.0.0.0
        - name: SERVER.PORT
          value: '8080'
        - name: SERVER.NAME
          valueFrom:
            secretKeyRef:
              key: "1.0"
              name: "TOKEN_SERVER_NAME"
        - name: PG.USER
          valueFrom:
            secretKeyRef:
              key: "1"
              name: "POSTGRES_USER"
        - name: PG.PASSWORD
          valueFrom:
            secretKeyRef:
              key: "1"
              name: "POSTGRES_PASSWORD"
        - name: PG.HOST
          valueFrom:
            secretKeyRef:
              key: "1"
              name: "POSTGRES_HOST"
        - name: PG.PORT
          valueFrom:
            secretKeyRef:
              key: "1"
              name: "POSTGRES_PORT"
        - name: PG.DBNAME
          valueFrom:
            secretKeyRef:
              key: "1"
              name: "POSTGRES_DBNAME"
