apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER.NAME
              value: tokenissuer.nl
            - name: SERVER.PORT
              value: "8080"
            - name: SERVER.HOST
              value: "0.0.0.0"
            - name: PG.HOST
              value: {{ .Values.cb.databaseHost }}
            - name: PG.PORT
              value: "5432"
            - name: PG.USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-creds
            - name: PG.PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-creds
            - name: PG.DBNAME
              valueFrom:
                secretKeyRef:
                  key: database
                  name: postgres-creds
            - name: PG.POOL.MAX_SIZE
              value: "30"
            - name: BOOTSTRAP
              value: "false"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 64Mi
