apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SERVER.NAME
            value: tokenissuer.nl
          - name: SERVER.PORT
            value: "8080"
          - name: SERVER.HOST
            value: "0.0.0.0"
          - name: PG.HOST
            value: postgres
          - name: PG.PORT
            value: "5432"
          - name: PG.USER
            value: postgres
          - name: PG.PASSWORD
            value: postgres
          - name: PG.DBNAME
            value: postgres
          - name: PG.POOL.MAX_SIZE
            value: "30"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "100Mi"
