apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: oauth2-tokenserver
spec:
  template:
    spec:
      containers:
      - image: rlemmens/oauth2-server-rs:0.3.3
        env:
        - name: SERVER.HOST
          value: "0.0.0.0"
        - name: SERVER.PORT
          value: "8080"
        - name: SERVER.NAME
          value: "oauth2-tokenserver-rs"
        - name: PG.USER
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres-creds
        - name: PG.PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-creds
        - name: PG.HOST
          valueFrom:
            configMapKeyRef:
              key: host
              name: oauth2-cm
        - name: PG.PORT
          valueFrom:
            configMapKeyRef:
              key: port
              name: oauth2-cm
        - name: PG.DBNAME
          valueFrom:
            secretKeyRef:
              key: database
              name: postgres-creds
        - name: PG.POOL.MAX_SIZE
          value: "30"
        - name: bootstrap
          value: "true"
